### ISSUE TITLE
Allow merging masks without re-masking 

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/breizorro#35]
It would be nice to be able to merge two masks from previous runs, and do nothing else.

**Comment by IanHeywood** [comment]
Until this feature is implemented (or not) here is a short script that just uses numpy's logical operations on two Boolean FITS images.

https://github.com/IanHeywood/oxkat/blob/master/tools/image_logic.py

So to merge two masks with logical OR you can just do something like:

```
$ python image_logic.py mask1.fits OR mask2.fits mergedmask.fits
```

**Comment by o-smirnov** [comment]
You can already do that. Use ``-m mask1.fits --merge mask2.fits -o output.fits``.

**Comment by SpheMakh** [comment]
Awesome! Thanks
