### ISSUE TITLE
add option to dilate mask

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/breizorro#5]
And perhaps other useful functions from ``scipy.ndimage.morphology``.

**Comment by IanHeywood** [comment]
Dilation is already in:

https://github.com/ratt-ru/breizorro/blob/main/breizorro.py#L92

**Comment by o-smirnov** [comment]
Aha! Well, I'll leave this open, as I also have in mind a "take existing mask and dilate" mode. Basically evolving this into a set of handy mask manipulation utilities (think fitstool.py for masks...)

**Comment by IanHeywood** [comment]
> think fitstool.py for masks...

Totally with you on that one. I've got various bits of useful masking code lying around all over the place, e.g.

https://github.com/IanHeywood/oxkat/blob/master/tools/merge_FITS_masks.py
https://github.com/IanHeywood/oxkat/blob/master/tools/make_threshold_mask.py
https://github.com/IanHeywood/oxkat/blob/master/tools/mask_FITS_with_region.py

I did have another one somewhere that did thresholding within a region, which was useful when there was something very extended off to one side but you still wanted the benefits of the automasking for the rest of the field...
