### ISSUE TITLE
add option to fill in holes

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/breizorro#9]
My uncleanable galaxy results in a mask with a hole (Holy Mask? Donut Mask?):

| | |
|-|-|
|![im2-ksol-MFS-image fits-image-2021-1-25-11-15-0](https://user-images.githubusercontent.com/6470079/105685324-9cc82a80-5efe-11eb-8224-93b1924e80c2.png)|![mask-thr-dil2 fits-image-2021-1-25-11-17-22](https://user-images.githubusercontent.com/6470079/105685600-ed3f8800-5efe-11eb-91c3-1ceb0e1d7fa1.png)|

I will add an option to fill in holes in the mask (this is a one-liner). Any opinion on whether this should be on or off by default?

**Comment by IanHeywood** [comment]
I'd vote for off, as circular shells are a thing.

**Comment by o-smirnov** [comment]
Seconded.
